In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
raw = pd.read_csv('../Dataset/NetFlix.csv')

In [3]:
raw.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

In [4]:
raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   str
 1   type          7787 non-null   str
 2   title         7787 non-null   str
 3   director      5398 non-null   str
 4   cast          7069 non-null   str
 5   country       7280 non-null   str
 6   date_added    7777 non-null   str
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   str
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   str
 11  description   7787 non-null   str
dtypes: int64(2), str(10)
memory usage: 730.2 KB

In [5]:
temp = raw.dropna()

In [6]:
temp.info()

<class 'pandas.DataFrame'>
Index: 4808 entries, 1 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4808 non-null   str
 1   type          4808 non-null   str
 2   title         4808 non-null   str
 3   director      4808 non-null   str
 4   cast          4808 non-null   str
 5   country       4808 non-null   str
 6   date_added    4808 non-null   str
 7   release_year  4808 non-null   int64
 8   rating        4808 non-null   str
 9   duration      4808 non-null   int64
 10  genres        4808 non-null   str
 11  description   4808 non-null   str
dtypes: int64(2), str(10)
memory usage: 488.3 KB

In [7]:
temp.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
5,s1002,Movie,Blue Ruin,Jeremy Saulnier,"Macon Blair, Devin Ratray, Amy Hargreaves, Kev...","United States, France",25-Feb-19,2013,R,90,"Independent Movies, Thrillers",Bad news from the past unhinges vagabond Dwigh...
6,s1003,Movie,Blue Streak,Les Mayfield,"Martin Lawrence, Luke Wilson, Peter Greene, Da...","Germany, United States",1-Jan-21,1999,PG-13,94,"Action & Adventure, Comedies",A jewel thief returns to his hiding place afte...

In [8]:
temp.info()

<class 'pandas.DataFrame'>
Index: 4808 entries, 1 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4808 non-null   str
 1   type          4808 non-null   str
 2   title         4808 non-null   str
 3   director      4808 non-null   str
 4   cast          4808 non-null   str
 5   country       4808 non-null   str
 6   date_added    4808 non-null   str
 7   release_year  4808 non-null   int64
 8   rating        4808 non-null   str
 9   duration      4808 non-null   int64
 10  genres        4808 non-null   str
 11  description   4808 non-null   str
dtypes: int64(2), str(10)
memory usage: 488.3 KB

In [9]:
temp['date_added'] = pd.to_datetime(temp['date_added'])
temp.info()

C:\Users\aroma\AppData\Local\Temp\ipykernel_22024\3719330666.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp['date_added'] = pd.to_datetime(temp['date_added'])

<class 'pandas.DataFrame'>
Index: 4808 entries, 1 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4808 non-null   str
 1   type          4808 non-null   str
 2   title         4808 non-null   str
 3   director      4808 non-null   str
 4   cast          4808 non-null   str
 5   country       4808 non-null   str
 6   date_added    4808 non-null   datetime64[us]
 7   release_year  4808 non-null   int64
 8   rating        4808 non-null   str
 9   duration      4808 non-null   int64
 10  genres        4808 non-null   str
 11  description   4808 non-null   str
dtypes: datetime64[us](1), int64(2), str(9)
memory usage: 488.3 KB

In [10]:
columns = list(temp.columns)
columns.remove('date_added')
columns.remove('release_year')
columns.remove('duration')

temp[columns] = temp[columns].apply(lambda x : x.str.lower())

In [11]:
temp.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
1,s10,movie,1920,vikram bhatt,"rajneesh duggal, adah sharma, indraneil sengup...",india,2017-12-15,2008,tv-ma,143,"horror movies, international movies, thrillers",an architect and his wife move into a castle t...
2,s100,movie,3 heroines,iman brotoseno,"reza rahadian, bunga citra lestari, tara basro...",indonesia,2019-01-05,2016,tv-pg,124,"dramas, international movies, sports movies",three indonesian women break records by becomi...
3,s1000,movie,blue mountain state: the rise of thadland,lev l. spiro,"alan ritchson, darin brooks, james cade, rob r...",united states,2016-03-01,2016,r,90,comedies,new nfl star thad buys his old teammates' belo...
5,s1002,movie,blue ruin,jeremy saulnier,"macon blair, devin ratray, amy hargreaves, kev...","united states, france",2019-02-25,2013,r,90,"independent movies, thrillers",bad news from the past unhinges vagabond dwigh...
6,s1003,movie,blue streak,les mayfield,"martin lawrence, luke wilson, peter greene, da...","germany, united states",2021-01-01,1999,pg-13,94,"action & adventure, comedies",a jewel thief returns to his hiding place afte...

In [12]:
temp['rating'].unique()

<StringArray>
[   'tv-ma',    'tv-pg',        'r',    'pg-13',    'tv-14',     'tv-g',
       'pg',    'tv-y7',       'nr',        'g', 'tv-y7-fv',     'tv-y',
       'ur',    'nc-17']
Length: 14, dtype: str

In [13]:
cleaned = temp.copy()

In [14]:
country = list(set(temp['country'].to_list()))

In [15]:
len(country)

544

In [16]:
t = 'united kingdom, united states, dominican republic'

t.split(',')

['united kingdom', ' united states', ' dominican republic']

In [17]:
temp.type.unique()

<StringArray>
['movie', 'tv show']
Length: 2, dtype: str

In [18]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    sparse_output = False
)
type_encodes = encoder.fit_transform(cleaned[['type']])
type_features = encoder.get_feature_names_out(['type'])
types_df = pd.DataFrame(type_encodes,columns = type_features)
types_df

      type_movie  type_tv show
0            1.0           0.0
1            1.0           0.0
2            1.0           0.0
3            1.0           0.0
4            1.0           0.0
...          ...           ...
4803         1.0           0.0
4804         1.0           0.0
4805         1.0           0.0
4806         1.0           0.0
4807         1.0           0.0

[4808 rows x 2 columns]

In [27]:
test = pd.concat([cleaned.reset_index(drop = True),types_df.reset_index(drop = True)],axis = 1)

In [28]:
test

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,type_movie,type_tv show
0,s10,movie,1920,vikram bhatt,"rajneesh duggal, adah sharma, indraneil sengup...",india,2017-12-15,2008,tv-ma,143,"horror movies, international movies, thrillers",an architect and his wife move into a castle t...,1.0,0.0
1,s100,movie,3 heroines,iman brotoseno,"reza rahadian, bunga citra lestari, tara basro...",indonesia,2019-01-05,2016,tv-pg,124,"dramas, international movies, sports movies",three indonesian women break records by becomi...,1.0,0.0
2,s1000,movie,blue mountain state: the rise of thadland,lev l. spiro,"alan ritchson, darin brooks, james cade, rob r...",united states,2016-03-01,2016,r,90,comedies,new nfl star thad buys his old teammates' belo...,1.0,0.0
3,s1002,movie,blue ruin,jeremy saulnier,"macon blair, devin ratray, amy hargreaves, kev...","united states, france",2019-02-25,2013,r,90,"independent movies, thrillers",bad news from the past unhinges vagabond dwigh...,1.0,0.0
4,s1003,movie,blue streak,les mayfield,"martin lawrence, luke wilson, peter greene, da...","germany, united states",2021-01-01,1999,pg-13,94,"action & adventure, comedies",a jewel thief returns to his hiding place afte...,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,s991,movie,blood will tell,"miguel cohan, miguel cohan","oscar martínez, dolores fonzi, diego velázquez...","argentina, united states",2019-06-21,2019,tv-ma,113,"dramas, independent movies, international movies",family patriarch elías begins to unravel after...,1.0,0.0
4804,s994,movie,blow,ted demme,"johnny depp, penélope cruz, franka potente, ra...",united states,2019-10-01,2001,r,123,dramas,cocaine smuggler george rises from poverty to ...,1.0,0.0
4805,s997,movie,blue is the warmest color,abdellatif kechiche,"léa seydoux, adèle exarchopoulos, salim kechio...","france, belgium, spain",2016-08-26,2013,nc-17,180,"dramas, independent movies, international movies","determined to fall in love, 15-year-old adele ...",1.0,0.0
4806,s998,movie,blue jasmine,woody allen,"cate blanchett, sally hawkins, alec baldwin, l...",united states,2019-03-08,2013,pg-13,98,"comedies, dramas, independent movies",the high life leads to high anxiety for a fash...,1.0,0.0
4807,s999,movie,blue jay,alex lehmann,"sarah paulson, mark duplass, clu gulager",united states,2016-12-06,2016,tv-ma,81,"dramas, independent movies, romantic movies",two former high school sweethearts unexpectedl...,1.0,0.0

In [30]:
cleaned = test.copy()

In [31]:
cleaned.rating.unique()

<StringArray>
[   'tv-ma',    'tv-pg',        'r',    'pg-13',    'tv-14',     'tv-g',
       'pg',    'tv-y7',       'nr',        'g', 'tv-y7-fv',     'tv-y',
       'ur',    'nc-17']
Length: 14, dtype: str

In [39]:
rating_encodes = encoder.fit_transform(cleaned[['rating']])
rating_types = encoder.get_feature_names_out()
rating_df = pd.DataFrame(rating_encodes,columns = rating_types)
rating_df

,rating_g,rating_nc-17,rating_nr,rating_pg,rating_pg-13,rating_r,rating_tv-14,rating_tv-g,rating_tv-ma,rating_tv-pg,rating_tv-y,rating_tv-y7,rating_tv-y7-fv,rating_ur
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4804,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4805,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4806,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4807,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [44]:
test = pd.concat([cleaned,rating_df],axis = 1)
cleaned = test.copy()

In [45]:
cleaned

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,rating_pg-13,rating_r,rating_tv-14,rating_tv-g,rating_tv-ma,rating_tv-pg,rating_tv-y,rating_tv-y7,rating_tv-y7-fv,rating_ur
0,s10,movie,1920,vikram bhatt,"rajneesh duggal, adah sharma, indraneil sengup...",india,2017-12-15,2008,tv-ma,143,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,s100,movie,3 heroines,iman brotoseno,"reza rahadian, bunga citra lestari, tara basro...",indonesia,2019-01-05,2016,tv-pg,124,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,s1000,movie,blue mountain state: the rise of thadland,lev l. spiro,"alan ritchson, darin brooks, james cade, rob r...",united states,2016-03-01,2016,r,90,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,s1002,movie,blue ruin,jeremy saulnier,"macon blair, devin ratray, amy hargreaves, kev...","united states, france",2019-02-25,2013,r,90,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,s1003,movie,blue streak,les mayfield,"martin lawrence, luke wilson, peter greene, da...","germany, united states",2021-01-01,1999,pg-13,94,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,s991,movie,blood will tell,"miguel cohan, miguel cohan","oscar martínez, dolores fonzi, diego velázquez...","argentina, united states",2019-06-21,2019,tv-ma,113,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4804,s994,movie,blow,ted demme,"johnny depp, penélope cruz, franka potente, ra...",united states,2019-10-01,2001,r,123,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4805,s997,movie,blue is the warmest color,abdellatif kechiche,"léa seydoux, adèle exarchopoulos, salim kechio...","france, belgium, spain",2016-08-26,2013,nc-17,180,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4806,s998,movie,blue jasmine,woody allen,"cate blanchett, sally hawkins, alec baldwin, l...",united states,2019-03-08,2013,pg-13,98,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4807,s999,movie,blue jay,alex lehmann,"sarah paulson, mark duplass, clu gulager",united states,2016-12-06,2016,tv-ma,81,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [46]:
cleaned['country'] = cleaned['country'].str.split(',')
cleaned = cleaned.explode('country')
cleaned.country.unique()

<StringArray>
[         'india',      'indonesia',  'united states',        ' france',
        'germany', ' united states',         'canada',        'denmark',
        ' sweden',        ' israel',
 ...
       'paraguay',          ' iran',        'somalia',         ' sudan',
        ' panama',      ' slovenia',  ' east germany',        'namibia',
        'croatia',    ' montenegro']
Length: 165, dtype: str

In [49]:
freq = cleaned['country'].value_counts(normalize = True)
cleaned['country_freq'] = cleaned['country'].map(freq)

In [50]:
cleaned['country_freq']

0       0.140671
1       0.011885
2       0.306578
3       0.306578
3       0.019700
          ...
4805    0.021654
4805    0.010583
4805    0.005698
4806    0.306578
4807    0.306578
Name: country_freq, Length: 6142, dtype: float64