In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Dataset/orders.csv')

In [3]:
df.head()

,order_id,customer_name,product,category,quantity,unit_price,total_price,order_date,payment_method,status,rating
0,ORD-1001,Arun Kumar,Wireless Mouse,Electronics,2,$25.99,51.98,2024-01-15,Credit Card,Delivered,4.5
1,ORD-1002,Priya Nair,wireless mouse,electronics,3,25.99,77.97,15/01/2024,credit card,delivered,5
2,ORD1003,Rahul Menon,Mechanical Keyboard,Electronics,1,$89.50,89.50,2024/01/20,UPI,DELIVERED,4
3,ORD-1004,Sneha Das,Laptop Stand,Electronics,0,$45,0.00,2024-02-30,upi,Pending,NaN
4,ORD-1005,Vijay Kumar,USB-C Cable,Accessories,-2,$12.99,-25.98,March 5 2024,Cash,Cancelled,3

In [4]:
df.describe()

        total_price
count     49.000000
mean    1254.565102
std     5055.925704
min      -25.980000
25%       77.970000
50%      149.970000
75%      250.000000
max    25948.010000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     str
 1   customer_name   50 non-null     str
 2   product         49 non-null     str
 3   category        50 non-null     str
 4   quantity        48 non-null     str
 5   unit_price      50 non-null     str
 6   total_price     49 non-null     float64
 7   order_date      50 non-null     str
 8   payment_method  50 non-null     str
 9   status          50 non-null     str
 10  rating          46 non-null     str
dtypes: float64(1), str(10)
memory usage: 4.4 KB

### order_id

In [6]:
df.order_id = df.order_id.str.replace('ORD','')

In [7]:
df.order_id = df.order_id.str.replace('-','')

In [8]:
df.order_id = df.order_id.astype('int64')

In [9]:
df.order_id.unique()

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
       1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022,
       1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033,
       1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044,
       1045, 1046, 1047, 1048, 1049, 1050])

### customer_name

In [10]:
df.customer_name = df.customer_name.str.strip()

In [11]:
df.customer_name = df.customer_name.str.replace('Unknown','Unknown Last')

In [12]:
df[['first_name', 'last_name']] = df['customer_name'].str.split(expand=True)

In [13]:
col_name = df.columns.to_list()
col_name.remove('first_name')
col_name.remove('last_name')
col_name.insert(1,'first_name')
col_name.insert(2,'last_name')
df = df[col_name]

In [14]:
df.drop('customer_name',axis = 1,inplace = True)

### product

In [15]:
df.head()

,order_id,first_name,last_name,product,category,quantity,unit_price,total_price,order_date,payment_method,status,rating
0,1001,Arun,Kumar,Wireless Mouse,Electronics,2,$25.99,51.98,2024-01-15,Credit Card,Delivered,4.5
1,1002,Priya,Nair,wireless mouse,electronics,3,25.99,77.97,15/01/2024,credit card,delivered,5
2,1003,Rahul,Menon,Mechanical Keyboard,Electronics,1,$89.50,89.50,2024/01/20,UPI,DELIVERED,4
3,1004,Sneha,Das,Laptop Stand,Electronics,0,$45,0.00,2024-02-30,upi,Pending,NaN
4,1005,Vijay,Kumar,USB-C Cable,Accessories,-2,$12.99,-25.98,March 5 2024,Cash,Cancelled,3

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     int64
 1   first_name      50 non-null     str
 2   last_name       50 non-null     str
 3   product         49 non-null     str
 4   category        50 non-null     str
 5   quantity        48 non-null     str
 6   unit_price      50 non-null     str
 7   total_price     49 non-null     float64
 8   order_date      50 non-null     str
 9   payment_method  50 non-null     str
 10  status          50 non-null     str
 11  rating          46 non-null     str
dtypes: float64(1), int64(1), str(10)
memory usage: 4.8 KB

In [17]:
df['product'].unique()

<StringArray>
[     'Wireless Mouse',     'wireless mouse ', 'Mechanical Keyboard',
        'Laptop Stand',         'USB-C Cable',         'usb c cable',
             'Monitor',            'monitor ',              'Laptop',
          'Headphones',   'Bluetooth Speaker',  'bluetooth speaker ',
         'Smart Watch',          'Smartwatch',          'Power Bank',
           'powerbank',              'Webcam',             'Web Cam',
        'External HDD',  'external hard disk',                 'SSD',
                'ssd ',        'Gaming Mouse',        'gaming mouse',
            'Keyboard',          'Phone Case',          'phonecase ',
              'Tablet',             'Printer',            'printer ',
              'Router',         'WiFi Router',      'Ethernet Cable',
     'ethernet cable ',      'Laptop Charger',      'laptop charger',
          'Microphone',         'micro phone',              'Camera',
             'camera ',               'Drone',             'USB Hub',
             'usb hub',                   nan]
Length: 44, dtype: str

In [18]:
df['product'] = df['product'].str.strip().str.title()

In [20]:
df.drop(48,axis = 0)

,order_id,first_name,last_name,product,category,quantity,unit_price,total_price,order_date,payment_method,status,rating
0,1001,Arun,Kumar,Wireless Mouse,Electronics,2,$25.99,51.98,2024-01-15,Credit Card,Delivered,4.5
1,1002,Priya,Nair,Wireless Mouse,electronics,3,25.99,77.97,15/01/2024,credit card,delivered,5
2,1003,Rahul,Menon,Mechanical Keyboard,Electronics,1,$89.50,89.50,2024/01/20,UPI,DELIVERED,4
3,1004,Sneha,Das,Laptop Stand,Electronics,0,$45,0.00,2024-02-30,upi,Pending,NaN
4,1005,Vijay,Kumar,Usb-C Cable,Accessories,-2,$12.99,-25.98,March 5 2024,Cash,Cancelled,3
5,1006,Anjali,Roy,Usb C Cable,accessories,5,12.99,64.95,2024-03-05,cash,DELIVERED,4.0
6,1007,Mohammed,Ali,Monitor,Electronics,1,"₹25,000",25000.00,05-03-2024,Credit card,Delivered,5
7,1008,Neha,Joseph,Monitor,Electronics,one,$300,300.00,2024.03.10,CARD,delivered,4
8,1009,Arjun,S,Laptop,electronics,1,"$1,200",1200.00,10/03/24,credit_card,Delivered,5
9,1010,Meera,Raj,Laptop,1,1,1200 USD,1200.00,2024-03-12,Credit Card,DELIVERED,4.8
10,1011,Rohan,Paul,Headphones,Electronics,2,$75,150.00,2024-03-15,UPI,Delivered,6
11,1012,Diya,Thomas,Bluetooth Speaker,electronics,3,$49.99,149.97,15-03-2024,upi,delivered,-1
12,1013,Kiran,Varma,Bluetooth Speaker,Electronics,3,49.99,149.97,2024/03/15,UPI,Delivered,4
13,1014,Asha,George,Smart Watch,Wearables,1,$199,199.00,2024-03-20,Credit Card,Shipped,4.2
14,1015,Ravi,Pillai,Smartwatch,wearable,1,$199,199.00,20/03/2024,credit card,SHIPPED,4
15,1016,Nikhil,John,Power Bank,Accessories,2,$39.99,79.98,2024-03-25,COD,Delivered,NaN
16,1017,Fathima,K,Powerbank,accessories,2,39.99,79.98,2024-03-25,Cash on Delivery,delivered,3.5
17,1018,Aditya,S,Webcam,Electronics,1,$60,60.00,2024-04-01,UPI,Returned,2
18,1019,Lakshmi,Devi,Web Cam,electronics,1,60,60.00,01/04/2024,upi,RETURNED,2.0
19,1020,Suresh,B,External Hdd,Storage,1,$89.99,89.99,2024-04-05,Credit Card,Delivered,4
20,1021,Jaya,Krishnan,External Hard Disk,storage,1,89.99,89.99,05/04/2024,CARD,delivered,4.5
21,1022,Anoop,K,Ssd,Storage,2,$110,220.00,2024-04-10,UPI,Delivered,5
22,1023,Sharon,Paul,Ssd,storage,2,110,220.00,2024-04-10,upi,Delivered,five
23,1024,Tony,Mathew,Gaming Mouse,Electronics,1,$59.99,59.99,2024-04-15,Credit Card,Delivered,4
24,1025,Tony,Mathew,Gaming Mouse,electronics,1,59.99,59.99,15/04/2024,credit card,delivered,4
25,1026,Binu,Thomas,Keyboard,Electronics,NaN,$40,80.00,2024-04-20,UPI,Delivered,3
26,1027,Reshma,R,Keyboard,electronics,2,40,80.00,2024-04-20,upi,DELIVERED,3
27,1028,Akash,Dev,Phone Case,Accessories,10,$15,150.00,2024-04-25,Cash,Delivered,4
28,1029,Nisha,M,Phonecase,accessories,10,15,150.00,25/04/2024,cash,delivered,4
29,1030,George,T,Tablet,Electronics,1,$500,500.00,2024-04-31,Credit Card,Pending,4
30,1031,Sanjay,P,Tablet,electronics,1,500,500.00,2024-05-01,CARD,Delivered,4
31,1032,Maya,S,Printer,Electronics,1,$250,250.00,2024-05-05,UPI,Delivered,3
32,1033,MAYA,S,Printer,electronics,1,250,250.00,05/05/2024,upi,DELIVERED,3
33,1034,Joseph,K,Router,Networking,2,$80,160.00,2024-05-10,Credit Card,Delivered,4
34,1035,Anna,Rose,Wifi Router,network,2,80,160.00,10/05/2024,credit card,Delivered,4
35,1036,Hari,Menon,Ethernet Cable,Accessories,5,$10,50.00,2024-05-15,Cash,Delivered,4
36,1037,hari,menon,Ethernet Cable,accessories,5,10,50.00,2024/05/15,cash,DELIVERED,4
37,1038,Deepa,K,Laptop Charger,Electronics,1,$75,75.00,2024-05-20,UPI,Cancelled,NaN
38,1039,Vivek,R,Laptop Charger,electronics,1,75,75.00,20-05-2024,upi,Delivered,4
39,1040,Anu,Paul,Microphone,Electronics,2,$99.99,199.98,2024-06-01,Credit Card,Delivered,5
40,1041,Rakesh,N,Micro Phone,electronics,2,99.99,199.98,01/06/2024,credit card,delivered,5
41,1042,Sara,John,Camera,1,1,$450,450.00,2024-06-05,UPI,Delivered,4
42,1043,Ben,George,Camera,Electronics,1,450,450.00,2024-06-05,upi,DELIVERED,4
43,1044,Irfan,K,Drone,Electronics,1,$800,800.00,2024-06-10,Credit Card,Delivered,10
44,1045,Kavya,S,Drone,electronics,1,800,800.00,10/06/2024,credit card,delivered,5
45,1046,Manu,P,Usb Hub,Accessories,3,$29.99,89.97,2024-06-15,UPI,Delivered,4
46,1047,Anjali,Roy,Usb Hub,accessories,3,29.99,89.97,15/06/2024,upi,delivered,4
47,1048,Rahul,Menon,Mechanical Keyboard,Electronics,1,$89.50,89.50,2024/01/20,UPI,DELIVERED,4
49,1050,Priya,Nair,Wireless Mouse,Electronics,999,$25.99,25948.01,2024-06-20,Credit Card,Delivered,4

### category

In [21]:
df.category.unique()

<StringArray>
['Electronics', 'electronics', 'Accessories', 'accessories',           '1',
   'Wearables',    'wearable',     'Storage',     'storage',  'Networking',
     'network',           '-']
Length: 12, dtype: str

In [27]:
df['category'] = df['category'].replace('1',np.nan)

In [29]:
df['category'] = df['category'].replace('-',np.nan)

In [32]:
df.category.unique()

<StringArray>
['Electronics', 'Accessories',           nan,   'Wearables',    'Wearable',
     'Storage',  'Networking',     'Network']
Length: 8, dtype: str

In [31]:
df.category = df.category.str.capitalize()

### quantity

In [33]:
df.head()

,order_id,first_name,last_name,product,category,quantity,unit_price,total_price,order_date,payment_method,status,rating
0,1001,Arun,Kumar,Wireless Mouse,Electronics,2,$25.99,51.98,2024-01-15,Credit Card,Delivered,4.5
1,1002,Priya,Nair,Wireless Mouse,Electronics,3,25.99,77.97,15/01/2024,credit card,delivered,5
2,1003,Rahul,Menon,Mechanical Keyboard,Electronics,1,$89.50,89.50,2024/01/20,UPI,DELIVERED,4
3,1004,Sneha,Das,Laptop Stand,Electronics,0,$45,0.00,2024-02-30,upi,Pending,NaN
4,1005,Vijay,Kumar,Usb-C Cable,Accessories,-2,$12.99,-25.98,March 5 2024,Cash,Cancelled,3

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     int64
 1   first_name      50 non-null     str
 2   last_name       50 non-null     str
 3   product         49 non-null     str
 4   category        47 non-null     str
 5   quantity        48 non-null     str
 6   unit_price      50 non-null     str
 7   total_price     49 non-null     float64
 8   order_date      50 non-null     str
 9   payment_method  50 non-null     str
 10  status          50 non-null     str
 11  rating          46 non-null     str
dtypes: float64(1), int64(1), str(10)
memory usage: 4.8 KB