In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Dataset/gpt_1.csv')

In [3]:
df.head()

,customer_id,name,age,gender,email,phone,city,join_date,salary,purchases,status
0,1001,John Smith,25,M,john.smith@gmail.com,9876543210,New York,2023-01-15,"$45,000",12,Active
1,1002,alice johnson,30,F,alice.j@gmail.com,+1-555-234-5678,los angeles,15/02/2023,52000,8,active
2,1003,Bob Williams,NaN,Male,bob.williams@gmail,5551234567,Chicago,2023/03/10,"48,500",15,ACTIVE
3,1004,CHARLIE BROWN,-5,m,charlie@email.com,(555) 987-1234,Houston,10-04-2023,$60000,20,Inactive
4,1005,David Miller,29,M,NaN,555.222.3333,Phoenix,April 12 2023,"$55,000",unknown,active

In [4]:
df.describe()

       customer_id
count     50.00000
mean    1025.50000
std       14.57738
min     1001.00000
25%     1013.25000
50%     1025.50000
75%     1037.75000
max     1050.00000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  50 non-null     int64
 1   name         50 non-null     str
 2   age          45 non-null     str
 3   gender       50 non-null     str
 4   email        49 non-null     str
 5   phone        50 non-null     str
 6   city         50 non-null     str
 7   join_date    50 non-null     str
 8   salary       50 non-null     str
 9   purchases    50 non-null     str
 10  status       50 non-null     str
dtypes: int64(1), str(10)
memory usage: 4.4 KB

In [6]:
df['name'] = df['name'].str.capitalize()

In [7]:
df['name'] = df['name'].str.strip()

In [8]:
df['First Name'] = df['name'].apply(lambda x : x.split(' ')[0])

In [9]:
df['Last Name'] = df['name'].apply(lambda x : x.split(' ')[1])

In [10]:
df['Last Name'].isnull().sum()

np.int64(0)

In [11]:
df.drop('name',axis = 1,inplace = True)

In [12]:
cols = df.columns.to_list()
cols

['customer_id',
 'age',
 'gender',
 'email',
 'phone',
 'city',
 'join_date',
 'salary',
 'purchases',
 'status',
 'First Name',
 'Last Name']

In [13]:
cols.remove('First Name')
cols.remove('Last Name')
cols.insert(1,'First Name')
cols.insert(2,'Last Name')
cols

['customer_id',
 'First Name',
 'Last Name',
 'age',
 'gender',
 'email',
 'phone',
 'city',
 'join_date',
 'salary',
 'purchases',
 'status']

In [14]:
df = df[cols]

In [15]:
df.head()

,customer_id,First Name,Last Name,age,gender,email,phone,city,join_date,salary,purchases,status
0,1001,John,smith,25,M,john.smith@gmail.com,9876543210,New York,2023-01-15,"$45,000",12,Active
1,1002,alice,johnson,30,F,alice.j@gmail.com,+1-555-234-5678,los angeles,15/02/2023,52000,8,active
2,1003,Bob,williams,NaN,Male,bob.williams@gmail,5551234567,Chicago,2023/03/10,"48,500",15,ACTIVE
3,1004,Charlie,brown,-5,m,charlie@email.com,(555) 987-1234,Houston,10-04-2023,$60000,20,Inactive
4,1005,David,miller,29,M,NaN,555.222.3333,Phoenix,April 12 2023,"$55,000",unknown,active

In [16]:
df['email'].isnull().sum()

np.int64(1)

In [17]:
df[df['email'].str[-10:]!='@gmail.com']

,customer_id,First Name,Last Name,age,gender,email,phone,city,join_date,salary,purchases,status
2,1003,Bob,williams,NaN,Male,bob.williams@gmail,5551234567,Chicago,2023/03/10,"48,500",15,ACTIVE
3,1004,Charlie,brown,-5,m,charlie@email.com,(555) 987-1234,Houston,10-04-2023,$60000,20,Inactive
4,1005,David,miller,29,M,NaN,555.222.3333,Phoenix,April 12 2023,"$55,000",unknown,active
11,1012,Karen,walker,27,F,karen.walker@,5551112223,Los Angeles,2023-08-15,51000,14,ACTIVE
30,1031,Charlie,brown,45,M,charlie@email.com,5559871234,Houston,2023-04-10,"$60,000",20,Inactive

In [18]:
df['email'] = df['email'].apply(
    lambda x: (
        x if pd.isna(x) or x.endswith('@gmail.com')
        else x.split('@')[0] + '@gmail.com'
    )
)

In [19]:
df.head()

,customer_id,First Name,Last Name,age,gender,email,phone,city,join_date,salary,purchases,status
0,1001,John,smith,25,M,john.smith@gmail.com,9876543210,New York,2023-01-15,"$45,000",12,Active
1,1002,alice,johnson,30,F,alice.j@gmail.com,+1-555-234-5678,los angeles,15/02/2023,52000,8,active
2,1003,Bob,williams,NaN,Male,bob.williams@gmail.com,5551234567,Chicago,2023/03/10,"48,500",15,ACTIVE
3,1004,Charlie,brown,-5,m,charlie@gmail.com,(555) 987-1234,Houston,10-04-2023,$60000,20,Inactive
4,1005,David,miller,29,M,NaN,555.222.3333,Phoenix,April 12 2023,"$55,000",unknown,active

In [20]:
df['email'] = df['email'].fillna(df['First Name'].str.lower()+'.'+df['Last Name'].str.lower()+'.'+'@gmail.com')

In [21]:
df['age'] = df['age'].replace('unknown',np.nan)

In [22]:
df['age'] = df['age'].fillna(df['age'].mode()[0])

In [23]:
df['age'] = df['age'].astype('int64')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  50 non-null     int64
 1   First Name   50 non-null     str
 2   Last Name    50 non-null     str
 3   age          50 non-null     int64
 4   gender       50 non-null     str
 5   email        50 non-null     str
 6   phone        50 non-null     str
 7   city         50 non-null     str
 8   join_date    50 non-null     str
 9   salary       50 non-null     str
 10  purchases    50 non-null     str
 11  status       50 non-null     str
dtypes: int64(2), str(10)
memory usage: 4.8 KB

In [25]:
df['age'].unique()

array([ 25,  30,  28,  -5,  29,  35, 150,  32,  31,  27,  26,  34,  33,
        40,  24,  36,  22,  45,  38,  39,  37, 999])

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  50 non-null     int64
 1   First Name   50 non-null     str
 2   Last Name    50 non-null     str
 3   age          50 non-null     int64
 4   gender       50 non-null     str
 5   email        50 non-null     str
 6   phone        50 non-null     str
 7   city         50 non-null     str
 8   join_date    50 non-null     str
 9   salary       50 non-null     str
 10  purchases    50 non-null     str
 11  status       50 non-null     str
dtypes: int64(2), str(10)
memory usage: 4.8 KB

In [31]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [32]:
df.loc[df['age'] > 120, 'age'] = df['age'].mode()[0]

In [37]:
df.loc[df['age'] < 1,'age'] = df['age'].mode()[0]

In [ ]:
df.isna().sum()

In [ ]:
df['age'].dtype

In [36]:
df

,customer_id,First Name,Last Name,age,gender,email,phone,city,join_date,salary,purchases,status
0,1001.0,John,smith,25,M,john.smith@gmail.com,9876543210,New York,2023-01-15,"$45,000",12,Active
1,1002.0,alice,johnson,30,F,alice.j@gmail.com,+1-555-234-5678,los angeles,15/02/2023,52000,8,active
2,1003.0,Bob,williams,28,Male,bob.williams@gmail.com,5551234567,Chicago,2023/03/10,"48,500",15,ACTIVE
3,28.0,Charlie,brown,28,m,charlie@gmail.com,(555) 987-1234,Houston,10-04-2023,$60000,20,Inactive
4,1005.0,David,miller,29,M,david.miller.@gmail.com,555.222.3333,Phoenix,April 12 2023,"$55,000",unknown,active
5,1006.0,Emily,davis,35,F,emily.davis@gmail.com,9876543211,New York,2023-05-01,62000,18,Active
6,1007.0,Frank,wilson,28,M,frankwilson@gmail.com,123456,Boston,2023/05/14,70000,25,ACTIVE
7,1008.0,Grace,taylor,32,Female,grace.taylor@gmail.com,+91 98765 43210,Miami,14-06-2023,"$68,000",22,active
8,1009.0,Henry,moore,28,M,henry.moore@gmail.com,555-444-8888,Chicago,2023-06-20,"65,000",19,Inactive
9,1010.0,Isabella,clark,28,F,isabella.clark@gmail.com,5554449999,Seattle,20/07/2023,58000,16,Active
10,1011.0,Jack,lewis,31,M,jack.lewis@gmail.com,+1 555 111 2222,new york,2023.08.01,"$72,000",30,active
11,1012.0,Karen,walker,27,F,karen.walker@gmail.com,5551112223,Los Angeles,2023-08-15,51000,14,ACTIVE
12,1013.0,Liam,hall,28,M,liam.hall@gmail.com,5551112224,Chicago,2023-09-01,"$49,000",9,Inactive
13,1014.0,Mia,allen,26,F,mia.allen@gmail.com,5551112225,Boston,2023-09-18,53000,17,active
14,1015.0,Noah,young,34,M,noah.young@gmail.com,5551112226,Houston,2023-10-05,"$61,000",21,Active
15,1016.0,Olivia,king,29,F,olivia.king@gmail.com,5551112227,Phoenix,2023-10-20,59000,13,active
16,1017.0,Peter,wright,28,M,peter.wright@gmail.com,5551112228,Miami,2023-11-01,"$64,000",18,Inactive
17,1018.0,Quinn,scott,33,F,quinn.scott@gmail.com,5551112229,Seattle,01-11-2023,"67,500",20,Active
18,1019.0,Ryan,green,40,M,ryan.green@gmail.com,5551112230,New York,2023/11/15,"$75,000",35,ACTIVE
19,1020.0,Sophia,adams,24,F,sophia.adams@gmail.com,5551112231,Los angeles,2023-12-01,47000,10,active
20,1021.0,Tom,baker,31,M,tom.baker@gmail.com,5551112232,Chicago,2023-12-15,"$58,000",-2,Active
21,1022.0,Uma,carter,28,F,uma.carter@gmail.com,5551112233,Boston,2024-01-01,52k,12,Inactive
22,1023.0,Victor,perez,36,M,victor.perez@gmail.com,5551112234,Houston,2024-01-10,"$66,000",24,ACTIVE
23,1024.0,Wendy,turner,27,F,wendy.turner@gmail.com,5551112235,Phoenix,2024-01-20,54000,15,active
24,1025.0,Xavier,collins,28,M,xavier.collins@gmail.com,5551112236,Miami,2024-02-01,"$71,000",28,Active
25,1026.0,Yara,stewart,30,F,yara.stewart@gmail.com,5551112237,Seattle,2024-02-14,"$63,000",19,Inactive
26,1027.0,Zack,morris,22,M,zack.morris@gmail.com,5551112238,New York,2024-02-30,"$42,000",7,active
27,1028.0,John,smith,25,M,john.smith@gmail.com,9876543210,New york,2023-01-15,45000,12,Active
28,1029.0,Alice,johnson,30,F,alice.j@gmail.com,+1-555-234-5678,Los Angeles,2023-02-15,52000,8,ACTIVE
29,1030.0,Bob,williams,28,M,bob.williams@gmail.com,5551234567,Chicago,10/03/2023,"48,500",15,active
30,1031.0,Charlie,brown,45,M,charlie@gmail.com,5559871234,Houston,2023-04-10,"$60,000",20,Inactive
31,1032.0,David,miller,29,M,david.miller@gmail.com,5552223333,Phoenix,2023-04-12,55000,11,Active
32,1033.0,Emily,davis,35,F,emily.davis@gmail.com,9876543211,New York,2023-05-01,62000,18,Active
33,1034.0,Frank,wilson,38,M,frankwilson@gmail.com,5557778888,Boston,2023-05-14,70000,25,active
34,1035.0,Grace,taylor,32,F,grace.taylor@gmail.com,9876543212,Miami,2023-06-14,"$68,000",22,ACTIVE
35,1036.0,Henry,moore,39,M,henry.moore@gmail.com,5554448888,Chicago,2023-06-20,"65,000",19,Inactive
36,1037.0,Isabella,clark,28,F,isabella.clark@gmail.com,5554449999,Seattle,2023-07-20,58000,16,Active
37,1038.0,Jack,lewis,31,M,jack.lewis@gmail.com,5551112222,New York,2023-08-01,72000,30,active
38,1039.0,Karen,walker,27,F,karen.walker@gmail.com,5551112223,Los Angeles,2023-08-15,"51,000",14,ACTIVE
39,1040.0,Liam,hall,33,M,liam.hall@gmail.com,5551112224,Chicago,2023-09-01,49000,9,Inactive
40,1041.0,Mia,allen,26,F,mia.allen@gmail.com,5551112225,Boston,2023-09-18,53000,17,active
41,1042.0,Noah,young,34,M,noah.young@gmail.com,5551112226,Houston,2023-10-05,"$61,000",21,Active
42,1043.0,Olivia,king,29,F,olivia.king@gmail.com,5551112227,Phoenix,2023-10-20,59000,13,active
43,1044.0,Peter,wright,37,M,peter.wright@gmail.com,5551112228,Miami,2023-11-01,64000,18,Inactive
44,1045.0,Quinn,scott,33,F,quinn.scott@gmail.com,5551112229,Seattle,2023-11-01,"67,500",20,Active
45,1046.0,Ryan,green,40,M,ryan.green@gmail.com,5551112230,New York,2023-11-15,$75000,35,ACTIVE
46,1047.0,Sophia,adams,24,F,sophia.adams@gmail.com,5551112231,Los Angeles,2023-12-01,47000,10,active
47,1048.0,Tom,baker,31,M,tom.baker@gmail.com,5551112232,Chicago,2023-12-15,"58,000",0,Active
48,1049.0,Uma,carter,28,F,uma.carter@gmail.com,5551112233,Boston,2024-01-01,52000,12,Inactive
49,1050.0,Victor,perez,28,M,victor.perez@gmail.com,5551112234,Houston,2024-01-10,"$660,000",24,ACTIVE

In [38]:
df['Last Name'] = df['Last Name'].str.capitalize()

In [48]:
df.head()

,customer_id,First Name,Last Name,age,gender,email,phone,city,join_date,salary,purchases,status
0,1001.0,John,Smith,25,Male,john.smith@gmail.com,9876543210,New York,2023-01-15,"$45,000",12,Active
1,1002.0,alice,Johnson,30,Female,alice.j@gmail.com,+1-555-234-5678,los angeles,15/02/2023,52000,8,active
2,1003.0,Bob,Williams,28,Male,bob.williams@gmail.com,5551234567,Chicago,2023/03/10,"48,500",15,ACTIVE
3,28.0,Charlie,Brown,28,Male,charlie@gmail.com,(555) 987-1234,Houston,10-04-2023,$60000,20,Inactive
4,1005.0,David,Miller,29,Male,david.miller.@gmail.com,555.222.3333,Phoenix,April 12 2023,"$55,000",unknown,active

In [46]:
df.loc[(df['gender'] == 'M') | (df['gender'] == 'm'),'gender'] = 'Male'

In [43]:
df.loc[df['gender'] == 'F','gender'] = 'Female'

In [47]:
df.gender.unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [59]:
df.city.unique()

<StringArray>
[   'New york', 'Los angeles',     'Chicago',     'Houston',     'Phoenix',
      'Boston',       'Miami',     'Seattle']
Length: 8, dtype: str

In [51]:
df.city = df.city.str.lower()

In [54]:
df.city = df.city.str.capitalize()

In [55]:
df.city = df.city.str.strip()

In [90]:
df['city'] = df['city'].str.strip().str.title()
df

,customer_id,First Name,Last Name,age,gender,email,phone,city,join_date,salary,purchases,status
0,1001.0,John,Smith,25,Male,john.smith@gmail.com,9876543210,New York,2023-01-15,45000,12,Active
1,1002.0,alice,Johnson,30,Female,alice.j@gmail.com,NaN,Los Angeles,15/02/2023,52000,8,active
2,1003.0,Bob,Williams,28,Male,bob.williams@gmail.com,5551234567,Chicago,2023/03/10,48500,15,ACTIVE
3,28.0,Charlie,Brown,28,Male,charlie@gmail.com,5559871234,Houston,10-04-2023,60000,20,Inactive
4,1005.0,David,Miller,29,Male,david.miller.@gmail.com,5552223333,Phoenix,April 12 2023,55000,unknown,active
5,1006.0,Emily,Davis,35,Female,emily.davis@gmail.com,9876543211,New York,2023-05-01,62000,18,Active
6,1007.0,Frank,Wilson,28,Male,frankwilson@gmail.com,123456,Boston,2023/05/14,70000,25,ACTIVE
7,1008.0,Grace,Taylor,32,Female,grace.taylor@gmail.com,NaN,Miami,14-06-2023,68000,22,active
8,1009.0,Henry,Moore,28,Male,henry.moore@gmail.com,5554448888,Chicago,2023-06-20,65000,19,Inactive
9,1010.0,Isabella,Clark,28,Female,isabella.clark@gmail.com,5554449999,Seattle,20/07/2023,58000,16,Active
10,1011.0,Jack,Lewis,31,Male,jack.lewis@gmail.com,NaN,New York,2023.08.01,72000,30,active
11,1012.0,Karen,Walker,27,Female,karen.walker@gmail.com,5551112223,Los Angeles,2023-08-15,51000,14,ACTIVE
12,1013.0,Liam,Hall,28,Male,liam.hall@gmail.com,5551112224,Chicago,2023-09-01,49000,9,Inactive
13,1014.0,Mia,Allen,26,Female,mia.allen@gmail.com,5551112225,Boston,2023-09-18,53000,17,active
14,1015.0,Noah,Young,34,Male,noah.young@gmail.com,5551112226,Houston,2023-10-05,61000,21,Active
15,1016.0,Olivia,King,29,Female,olivia.king@gmail.com,5551112227,Phoenix,2023-10-20,59000,13,active
16,1017.0,Peter,Wright,28,Male,peter.wright@gmail.com,5551112228,Miami,2023-11-01,64000,18,Inactive
17,1018.0,Quinn,Scott,33,Female,quinn.scott@gmail.com,5551112229,Seattle,01-11-2023,67500,20,Active
18,1019.0,Ryan,Green,40,Male,ryan.green@gmail.com,5551112230,New York,2023/11/15,75000,35,ACTIVE
19,1020.0,Sophia,Adams,24,Female,sophia.adams@gmail.com,5551112231,Los Angeles,2023-12-01,47000,10,active
20,1021.0,Tom,Baker,31,Male,tom.baker@gmail.com,5551112232,Chicago,2023-12-15,58000,-2,Active
21,1022.0,Uma,Carter,28,Female,uma.carter@gmail.com,5551112233,Boston,2024-01-01,52000,12,Inactive
22,1023.0,Victor,Perez,36,Male,victor.perez@gmail.com,5551112234,Houston,2024-01-10,66000,24,ACTIVE
23,1024.0,Wendy,Turner,27,Female,wendy.turner@gmail.com,5551112235,Phoenix,2024-01-20,54000,15,active
24,1025.0,Xavier,Collins,28,Male,xavier.collins@gmail.com,5551112236,Miami,2024-02-01,71000,28,Active
25,1026.0,Yara,Stewart,30,Female,yara.stewart@gmail.com,5551112237,Seattle,2024-02-14,63000,19,Inactive
26,1027.0,Zack,Morris,22,Male,zack.morris@gmail.com,5551112238,New York,2024-02-30,42000,7,active
27,1028.0,John,Smith,25,Male,john.smith@gmail.com,9876543210,New York,2023-01-15,45000,12,Active
28,1029.0,Alice,Johnson,30,Female,alice.j@gmail.com,NaN,Los Angeles,2023-02-15,52000,8,ACTIVE
29,1030.0,Bob,Williams,28,Male,bob.williams@gmail.com,5551234567,Chicago,10/03/2023,48500,15,active
30,1031.0,Charlie,Brown,45,Male,charlie@gmail.com,5559871234,Houston,2023-04-10,60000,20,Inactive
31,1032.0,David,Miller,29,Male,david.miller@gmail.com,5552223333,Phoenix,2023-04-12,55000,11,Active
32,1033.0,Emily,Davis,35,Female,emily.davis@gmail.com,9876543211,New York,2023-05-01,62000,18,Active
33,1034.0,Frank,Wilson,38,Male,frankwilson@gmail.com,5557778888,Boston,2023-05-14,70000,25,active
34,1035.0,Grace,Taylor,32,Female,grace.taylor@gmail.com,9876543212,Miami,2023-06-14,68000,22,ACTIVE
35,1036.0,Henry,Moore,39,Male,henry.moore@gmail.com,5554448888,Chicago,2023-06-20,65000,19,Inactive
36,1037.0,Isabella,Clark,28,Female,isabella.clark@gmail.com,5554449999,Seattle,2023-07-20,58000,16,Active
37,1038.0,Jack,Lewis,31,Male,jack.lewis@gmail.com,5551112222,New York,2023-08-01,72000,30,active
38,1039.0,Karen,Walker,27,Female,karen.walker@gmail.com,5551112223,Los Angeles,2023-08-15,51000,14,ACTIVE
39,1040.0,Liam,Hall,33,Male,liam.hall@gmail.com,5551112224,Chicago,2023-09-01,49000,9,Inactive
40,1041.0,Mia,Allen,26,Female,mia.allen@gmail.com,5551112225,Boston,2023-09-18,53000,17,active
41,1042.0,Noah,Young,34,Male,noah.young@gmail.com,5551112226,Houston,2023-10-05,61000,21,Active
42,1043.0,Olivia,King,29,Female,olivia.king@gmail.com,5551112227,Phoenix,2023-10-20,59000,13,active
43,1044.0,Peter,Wright,37,Male,peter.wright@gmail.com,5551112228,Miami,2023-11-01,64000,18,Inactive
44,1045.0,Quinn,Scott,33,Female,quinn.scott@gmail.com,5551112229,Seattle,2023-11-01,67500,20,Active
45,1046.0,Ryan,Green,40,Male,ryan.green@gmail.com,5551112230,New York,2023-11-15,75000,35,ACTIVE
46,1047.0,Sophia,Adams,24,Female,sophia.adams@gmail.com,5551112231,Los Angeles,2023-12-01,47000,10,active
47,1048.0,Tom,Baker,31,Male,tom.baker@gmail.com,5551112232,Chicago,2023-12-15,58000,0,Active
48,1049.0,Uma,Carter,28,Female,uma.carter@gmail.com,5551112233,Boston,2024-01-01,52000,12,Inactive
49,1050.0,Victor,Perez,28,Male,victor.perez@gmail.com,5551112234,Houston,2024-01-10,660000,24,ACTIVE

In [61]:
df.loc[df['salary'].str[0] == '$','salary'] = df['salary'].apply(lambda x : x[1:] if x.startswith('$') else x )

In [62]:
df.salary.unique()

<StringArray>
[ '45,000',   '52000',  '48,500',   '60000',  '55,000',   '62000',   '70000',
  '68,000',  '65,000',   '58000',  '72,000',  '51000 ',  '49,000',   '53000',
  '61,000',   '59000',  '64,000',  '67,500',  '75,000',   '47000',  '58,000',
     '52k',  '66,000',   '54000',  '71,000',  '63,000',  '42,000',   '45000',
  '60,000',   '55000',   '72000',  '51,000',   '49000',   '64000',   '75000',
 '660,000']
Length: 36, dtype: str

In [73]:
## Remove , from the str
df['salary'] = df['salary'].str.replace('k', '000')
df['salary'] = df['salary'].str.replace(',',"")

In [75]:
df.salary = df.salary.astype('int64')

In [76]:
df['salary'].unique()

array([ 45000,  52000,  48500,  60000,  55000,  62000,  70000,  68000,
        65000,  58000,  72000,  51000,  49000,  53000,  61000,  59000,
        64000,  67500,  75000,  47000,  66000,  54000,  71000,  63000,
        42000, 660000])

In [77]:
df['phone'] = df['phone'].str.replace(r'\D','',regex = True)

In [78]:
df.phone.unique()

<StringArray>
[  '9876543210',  '15552345678',   '5551234567',   '5559871234',
   '5552223333',   '9876543211',       '123456', '919876543210',
   '5554448888',   '5554449999',  '15551112222',   '5551112223',
   '5551112224',   '5551112225',   '5551112226',   '5551112227',
   '5551112228',   '5551112229',   '5551112230',   '5551112231',
   '5551112232',   '5551112233',   '5551112234',   '5551112235',
   '5551112236',   '5551112237',   '5551112238',   '5557778888',
   '9876543212',   '5551112222']
Length: 30, dtype: str

In [91]:
df.loc[df.phone.str.len() != 10,'phone'] = np.nan

In [92]:
df.phone.isna().sum()

np.int64(5)

In [95]:
df.join_date = pd.to_datetime(df.join_date,errors = 'coerce')

In [97]:
df.join_date.isnull().sum()

np.int64(12)

In [98]:
df.join_date = df.join_date.fillna(df.join_date.mode()[0])

In [101]:
df.purchases.unique()

<StringArray>
[     '12',       '8',      '15',      '20', 'unknown',      '18',      '25',
      '22',      '19',      '16',      '30',      '14',       '9',      '17',
      '21',      '13',      '35',      '10',      '-2',      '24',      '28',
       '7',      '11',       '0']
Length: 24, dtype: str

In [110]:
df.purchases = df.purchases.replace(np.nan,'0')

In [111]:
df.purchases = df.purchases.astype('int64')

In [113]:
df.customer_id = df.customer_id.astype('int64')

In [115]:
df.describe()

       customer_id        age            join_date       salary  purchases
count    50.000000  50.000000                   50      50.0000   50.00000
mean   1005.980000  30.460000  2023-09-19 08:09:36   70800.0000   16.68000
min      28.000000  22.000000  2023-01-15 00:00:00   42000.0000   -2.00000
25%    1013.250000  28.000000  2023-08-04 12:00:00   52000.0000   12.00000
50%    1025.500000  29.000000  2023-11-01 00:00:00   59000.0000   17.00000
75%    1037.750000  33.000000  2023-11-01 00:00:00   65750.0000   20.75000
max    1050.000000  45.000000  2024-02-14 00:00:00  660000.0000   35.00000
std     141.846783   4.665155                  NaN   85457.1142    7.93967

In [116]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  50 non-null     int64
 1   First Name   50 non-null     str
 2   Last Name    50 non-null     str
 3   age          50 non-null     int64
 4   gender       50 non-null     str
 5   email        50 non-null     str
 6   phone        45 non-null     str
 7   city         50 non-null     str
 8   join_date    50 non-null     datetime64[us]
 9   salary       50 non-null     int64
 10  purchases    50 non-null     int64
 11  status       50 non-null     str
dtypes: datetime64[us](1), int64(4), str(7)
memory usage: 4.8 KB

In [117]:
df.status = df.status.str.capitalize()

In [120]:
df.isna().sum()

customer_id    0
First Name     0
Last Name      0
age            0
gender         0
email          0
phone          5
city           0
join_date      0
salary         0
purchases      0
status         0
dtype: int64