In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../Dataset/OnlineRetail.csv",encoding='latin')

In [6]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [ ]:
df['Description']

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [10]:
df.duplicated(subset='StockCode').sum()

np.int64(537839)

In [11]:
len(df['StockCode'].unique())

4070

In [14]:
df1 = df[df['Description'].isnull()]
df1.info()

<class 'pandas.DataFrame'>
Index: 1454 entries, 622 to 538554
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1454 non-null   str
 1   StockCode    1454 non-null   str
 2   Description  0 non-null      str
 3   Quantity     1454 non-null   int64
 4   InvoiceDate  1454 non-null   str
 5   UnitPrice    1454 non-null   float64
 6   CustomerID   0 non-null      float64
 7   Country      1454 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 102.2 KB

In [19]:
stock_code = list(set(df1['StockCode'].to_list()))
len(stock_code)

960

In [16]:
df2 = df[~df['StockCode'].isnull()]
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [20]:
stock_code1 = list(set(df2['StockCode'].to_list()))
len(stock_code1)

4070

In [32]:
res = df.groupby('StockCode')['Description'].nunique()
print(res[res>1])

StockCode
10080           2
10133           2
15058A          2
15058C          2
16008           2
               ..
90195A          2
90210D          2
DCGS0003        2
DCGS0069        2
gift_0001_20    2
Name: Description, Length: 650, dtype: int64

In [29]:
res.info()

<class 'pandas.Series'>
Index: 4070 entries, 10002 to m
Series name: Description
Non-Null Count  Dtype
--------------  -----
4070 non-null   int64
dtypes: int64(1)
memory usage: 192.6+ KB

In [33]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [36]:
df['Description'] = df['Description'].fillna(
    df.groupby('StockCode')['Description'].transform(lambda x:x.mode().iloc[0] if not x.mode().empty else np.nan
))
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description       112
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [41]:
df.dropna(inplace = True)

In [42]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [47]:
df.describe(include = 'str')

,InvoiceNo,StockCode,Description,InvoiceDate,Country
count,406829,406829,406829,406829,406829
unique,22190,3684,3896,20460,37
top,576339,85123A,WHITE HANGING HEART T-LIGHT HOLDER,11/14/2011 15:27,United Kingdom
freq,542,2077,2070,543,361878

In [51]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'],format = '%m/%d/%Y %H:%M')

In [54]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object