In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as pyplot
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [56]:
path = "../Dataset/bank_marketing.csv"
df = pd.read_csv(path)

In [57]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5
1,56,admin.,married,secondary,no,45,no,no,unknown,5
2,41,technician,married,secondary,no,1270,yes,no,unknown,5
3,55,services,married,secondary,no,2476,yes,no,unknown,5
4,54,admin.,married,tertiary,no,184,no,no,unknown,5

In [8]:
df['contact'].unique()

<StringArray>
['unknown', 'cellular', 'telephone']
Length: 3, dtype: str

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  str
 2   marital    11162 non-null  str
 3   education  11162 non-null  str
 4   default    11162 non-null  str
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  str
 7   loan       11162 non-null  str
 8   contact    11162 non-null  str
 9   day        11162 non-null  int64
dtypes: int64(3), str(7)
memory usage: 872.2 KB

In [11]:
df.job.unique()

<StringArray>
[       'admin.',    'technician',      'services',    'management',
       'retired',   'blue-collar',    'unemployed',  'entrepreneur',
     'housemaid',       'unknown', 'self-employed',       'student']
Length: 12, dtype: str

In [19]:
df[df['job'] == 'unknown']

,age,job,marital,education,default,balance,housing,loan,contact,day
66,49,unknown,married,primary,no,341,yes,yes,unknown,15
668,52,unknown,married,unknown,no,5361,no,no,cellular,5
861,60,unknown,married,unknown,no,17297,no,no,cellular,26
1075,31,unknown,married,secondary,no,111,no,no,cellular,21
1091,34,unknown,single,secondary,no,859,no,no,cellular,28
...,...,...,...,...,...,...,...,...,...,...
9845,36,unknown,married,secondary,no,179,no,no,cellular,8
9976,43,unknown,married,primary,no,0,yes,no,cellular,9
10570,77,unknown,married,unknown,no,397,no,no,telephone,8
10660,54,unknown,married,unknown,no,390,no,no,cellular,20
10805,51,unknown,married,unknown,no,2642,no,no,cellular,29

In [20]:
df.loc[df['job'] == 'unknown','job'] = np.nan

In [22]:
df = df.dropna()

In [23]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5
1,56,admin.,married,secondary,no,45,no,no,unknown,5
2,41,technician,married,secondary,no,1270,yes,no,unknown,5
3,55,services,married,secondary,no,2476,yes,no,unknown,5
4,54,admin.,married,tertiary,no,184,no,no,unknown,5
...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20
11158,39,services,married,secondary,no,733,no,no,unknown,16
11159,32,technician,single,secondary,no,29,no,no,cellular,19
11160,43,technician,married,secondary,no,0,no,yes,cellular,8
11161,34,technician,married,secondary,no,0,no,no,cellular,9

In [25]:
df['marital'].unique()

<StringArray>
['married', 'single', 'divorced']
Length: 3, dtype: str

In [26]:
df['education'].unique()

<StringArray>
['secondary', 'tertiary', 'primary', 'unknown']
Length: 4, dtype: str

In [27]:
def get_unique_values(df):
    return {
        column: df[column].unique().tolist()
        for column in df.columns
    }

In [28]:
u_val = get_unique_values(df)

In [47]:
df.loc[df['education']=='unknown','education'] = np.nan
df = df.dropna()

In [48]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5
1,56,admin.,married,secondary,no,45,no,no,unknown,5
2,41,technician,married,secondary,no,1270,yes,no,unknown,5
3,55,services,married,secondary,no,2476,yes,no,unknown,5
4,54,admin.,married,tertiary,no,184,no,no,unknown,5
...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20
11158,39,services,married,secondary,no,733,no,no,unknown,16
11159,32,technician,single,secondary,no,29,no,no,cellular,19
11160,43,technician,married,secondary,no,0,no,yes,cellular,8
11161,34,technician,married,secondary,no,0,no,no,cellular,9

In [51]:
pd.crosstab(df["job"], df["loan"], normalize="index")
pd.crosstab(df["education"], df["loan"], normalize="index")

loan             no       yes
education
primary    0.863333  0.136667
secondary  0.841855  0.158145
tertiary   0.901599  0.098401
unknown    0.947686  0.052314

In [52]:
u_val['education']

['secondary', 'tertiary', 'primary', 'unknown']

In [53]:
u_val['job']

['admin.',
 'technician',
 'services',
 'management',
 'retired',
 'blue-collar',
 'unemployed',
 'entrepreneur',
 'housemaid',
 'self-employed',
 'student']

In [58]:
df = pd.get_dummies(
    df,
    columns=["job"],
    dtype=int
)

In [59]:
df

,age,marital,education,default,balance,housing,loan,contact,day,job_admin.,...,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown
0,59,married,secondary,no,2343,yes,no,unknown,5,1,...,0,0,0,0,0,0,0,0,0,0
1,56,married,secondary,no,45,no,no,unknown,5,1,...,0,0,0,0,0,0,0,0,0,0
2,41,married,secondary,no,1270,yes,no,unknown,5,0,...,0,0,0,0,0,0,0,1,0,0
3,55,married,secondary,no,2476,yes,no,unknown,5,0,...,0,0,0,0,0,1,0,0,0,0
4,54,married,tertiary,no,184,no,no,unknown,5,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,single,primary,no,1,yes,no,cellular,20,0,...,0,0,0,0,0,0,0,0,0,0
11158,39,married,secondary,no,733,no,no,unknown,16,0,...,0,0,0,0,0,1,0,0,0,0
11159,32,single,secondary,no,29,no,no,cellular,19,0,...,0,0,0,0,0,0,0,1,0,0
11160,43,married,secondary,no,0,no,yes,cellular,8,0,...,0,0,0,0,0,0,0,1,0,0
11161,34,married,secondary,no,0,no,no,cellular,9,0,...,0,0,0,0,0,0,0,1,0,0