In [58]:
import pandas as pd
import numpy as np

Series
labelling in series
pd.Series(list,index = ['x','y','z'])
creating the Series using the dict will make the key its index 
Dataframe
dataframe created similar to the dict the key becomes the feature name and the values under the key becomes entry
pd.Dataframe(dict)
read the csv file name to pandas
to_string() used to print the entire data base

## Series

In [5]:
data = [320,200,140,170]
series = pd.Series(data)
print(series)

0    320
1    200
2    140
3    170
dtype: int64

### Labelling

In [6]:
series = pd.Series(data,index=['x','y','z','o'])
print(series)

x    320
y    200
z    140
o    170
dtype: int64

In [7]:
print(series['z'])

140

### Seires using Dictionary

In [8]:
data = {
    'x':320,
    'y':200,
    'z':140,
    'o':170
}
series = pd.Series(data)
print(series)

x    320
y    200
z    140
o    170
dtype: int64

## DataFrame

In [12]:
data = {
    'roll-no' : [12,43,10,23],
    'name' : ['Aromal','Nether','Max Verstappan','Hitler']
}
df = pd.DataFrame(data)
print(df)

   roll-no            name
0       12          Aromal
1       43          Nether
2       10  Max Verstappan
3       23          Hitler

### Read CSV

In [16]:
df = pd.read_csv("../Dataset/StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
print(df.to_string())

In [18]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [19]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [20]:
df.shape

(1000, 8)

In [21]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [22]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [23]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [26]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [30]:
df.describe(include='str')

,gender,race/ethnicity,parental level of education,lunch,test preparation course
count,1000,1000,1000,1000,1000
unique,2,5,6,2,2
top,female,group C,some college,standard,none
freq,518,319,226,645,642

In [31]:
df.loc[3]

gender                                       male
race/ethnicity                            group A
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     47
reading score                                  57
writing score                                  44
Name: 3, dtype: object

In [35]:
df.loc[3,["lunch"]]

lunch    free/reduced
Name: 3, dtype: str

In [36]:
df.iloc[3,2]

"associate's degree"

In [39]:
df[df['math score'] > 90].describe(include='str')

,gender,race/ethnicity,parental level of education,lunch,test preparation course
count,50,50,50,50,50
unique,2,5,6,2,2
top,male,group E,associate's degree,standard,completed
freq,29,20,16,45,31

In [42]:
df[df['test preparation course'].isin(['completed'])]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [43]:
df['col_name'].between(val1,val2)

NameError: name 'between' is not defined

In [47]:
df.isnull().sum()

df.isna().sum().sum()

np.int64(0)

In [48]:
df.isnull().mean() * 100

gender                         0.0
race/ethnicity                 0.0
parental level of education    0.0
lunch                          0.0
test preparation course        0.0
math score                     0.0
reading score                  0.0
writing score                  0.0
dtype: float64

In [50]:
df.dropna(axis = 1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.dropna

In [51]:
# df.fillna(df['age'].mean())
# df.fillna(df['age'].median())
# df.fillna(df['City'].mode()[0])

In [52]:
df.ffill()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [53]:
df.bfill()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df.drop_duplicates()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [57]:
df.duplicated(subset=["gender"])

0      False
1       True
2       True
3      False
4       True
       ...
995     True
996     True
997     True
998     True
999     True
Length: 1000, dtype: bool

In [ ]:
df["Name"] = df["Name"].astype(str)

In [ ]:
df["date"] = pd.to_datetime(df["date"])

In [ ]:
df["name"] = df['name'].str.lower()

In [ ]:
df['name'].str.upper()
df['name'].str.capitalize()
df['name'].str.strip()
df["city"].str.replace('cochin','kochi')
df[df['name'].str.contains('john')]
df[df['name'].str.startswith('a')]
df[df['name'].str.endswith('l')]
df['name'].str.len()
df.rename(columns={"old name":"new name"},inplace=True)
df.columns = ["Name","Age","Salary"]
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.sort_values("Salary")
df.sort_values("Salary",ascending = False)
df['city'].unique()
df['city'].nunique()
df['city'].value_counts()

In [ ]:
df.replace({None:np.nan})

In [ ]:
head() first
tail() last
shape dimensions of the df (rows,columns)
columns display the name of each columns